### PR TITLE
Edits to tour page, help pages, and nav

### PR DESCRIPTION
**Pull request by koverholt**
- [x] Rename Legal page to Help / About
- [x] Move additional info content to help / about page
- [x] Product links on index page open in new tab
- [x] Secondary nav / toolbar for quick access to products / webmail interface

### CODE REVIEW

**Comment by kellobri** [comment]
Quick Links look really clean - I like it. 

You have col widths in the `RStudio Professional Products` section set to 3 right now. Is bumping them up to 4 so that they span the container a bad look?

**Comment by koverholt** [comment]
Thanks!

When I set the column widths to 4, it overflows the jumbotron and looks weird, but it's probably because I don't have an overall grid or container setup correctly.

`col-md-4`:

screen shot 2018-12-21 at 10 07 01 am

`col-md-3`:

screen shot 2018-12-21 at 10 08 47 am

**Comment by kellobri** [comment]
I think I fixed the overflow by removing the `<div class="container">` under `RStudio Professional Products`

**Comment by koverholt** [comment]
Nice, yes it looks like that does the trick. Fixed in 89f148c. Thanks!

**Comment by colearendt** [comment]
This looks awesome!! Thanks for the work on this y'all! 

Do you get a horizontal scroll bar when it doesn't seem like it should be necessary? (admittedly a pretty big nit-pick :smile: )

**Comment by koverholt** [comment]
I have not seen a horizontal scroll bar. Are you seeing on a certain page or element, or on the entire page? Or does it only show up at a certain browser size?

**Review by colearendt — APPROVED** [review]

**Comment by colearendt** [comment]
If I make the browser page (in FireFox) small enough, but still a good bit bigger than the content, I get a horizontal scroll-bar. Getting a screen shot has proven difficult... it may be part of bootstrap-centering shenanigans

I don't think it's worth holding up this PR on it. The scroll bar on the product tour is pretty nasty at certain sizes though 😆 This may be an Rmd issue - the content runs over / behind the menu

**Comment by koverholt** [comment]
I was able to reproduce what you are talking about only in FF when I resize the window. Poking around in the inspector didn't show anything obvious, and I confirmed it wasn't being caused by the `<div class="container">` that I removed earlier.

So yeah, will leave this issue for future work, but thanks for pointing it out!

**Pull request merged**
