### PR TITLE
Resource Page updates

### PR DESCRIPTION
**Pull request by kellobri**
Lots of weird font-awesome change stuff that I didn't want or intend to touch. May need to back out and start fresh just to make the intended resource file changes.

- [x] Resource page should be link-complete 
- [x] Added a revamped version of the RSC evaluation planning guide doc

### CODE REVIEW

**Review by koverholt — COMMENTED** [review]
Looking good!

The quote and diagram are nice. Once we get through this next iteration, we might consider moving those to the jumbotron in the index page. 👍 

I'm not sure that the `Create` and `Configure / Leverage` headings make sense to me given the items in those bins. Are there other headings that would describe the bins better?

The `RStudio Connect Server API Cookbook` seems out of place under the `Manage & Administer` box.

I think the Font Awesome output is just a byproduct of us using different versions of rmarkdown or its deps.

**Comment by kellobri** [comment]
@koverholt I included the API Cookbook under Manage & Admin because of the new chapters that will become available there next release. I could swap it out for a link to the collection of RSC support articles though. Thoughts?

**Comment by koverholt** [comment]
Yep, the API Cookbook seems a bit bare for now.

I like the idea of linking to the RSC KB articles or https://docs.rstudio.com/resources.html (although the scope there is much wider). Whichever you think is a better fit.

**Comment by koverholt** [comment]
I just realized the support docs and support FAQ are different, do you also want to link to https://support.rstudio.com/hc/en-us/sections/204688508-RStudio-Connect instead (or in addition to)?

**Comment by kellobri** [comment]
Ooh yeah - I did want that one instead

**Pull request merged**
